apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: debugger-pod
  template:
    metadata:
      labels:
        pod: debugger-pod
    spec:
      containers:
      - name: debugger-container
        image: panupongdeve/debugger:latest
